---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: integration

resources:
- namespace.yaml
- deployment.yaml
- hpa.yaml
- service.yaml
- ingress.yaml

images:
  - name: the-my-app
    newName: my.docker.registry.com/my-project/my-app
    newTag: latest
